### ISSUE TITLE
Parameter index error when using Linq

### ISSUE THREAD

**Issue by selstam** [nhibernate/NHibernate.Spatial#103]
Hi!

I have a linq query that looks like this:

`return session.Query<Entity>().Where(x => x.SourcePartner.PartnerId == _sourcePartnerId && x.Coordinates != null && x.Coordinates.Distance(_centerCoordinate) <= _withinDistance);`

This generates the following SQL where clause:

`where entity_."SourcePartner_id"=:p0 and (entity_."Coordinates" is not null) and ST_Distance(entity_."Coordinates"::text,:p1::text)<=:p2`

The parameter list becomes:

`Name:p1 - Value:5c5c7f46-8c44-4f94-98ce-a97401457112  Name:p2 - Value:POINT (0 0)  Name:p3 - Value:0,000898315284119522`

As you can see the parameter p0 is missing in the parameter list but all parameters are correct (except index starts at 1 instead of 0). This only happens when I use the x.Coordinates.Distance method in my Linq query.

Any suggestions?

**Comment by peetw** [comment]
Hi @selstam , unfortunately the `IsWithinDistance` spatial restriction is not yet implemented (see #61).

One workaround would be to buffer `_centerCoordinate` by `_withinDistance` and then check whether the entity geom is covered by the buffered center point. For example, using the `QueryOver` syntax:

    var bufferedCenterCoordinate = _centerCoordinate.Buffer(_withinDistance);

    return session.QueryOver<Entity>()
        .Where(x => x.SourcePartner.PartnerId == _sourcePartnerId)
        .And(x => x.Coordinates != null)
        .WhereSpatialRestrictionOn(x => x.Coordinates)
        .CoveredBy(bufferedCenterCoordinate)
        .List();

**Comment by peetw** [comment]
Out of interest, what type of database were you working with? I might take a look and see why the Linq provider was failing for this. It would also help if you have a reproducible test case you could share?

**Comment by peetw** [comment]
Actually, looking at our existing unit/integration tests, your original code _should_ work... Have you tried the code without the first conditional?

    return session.Query<Entity>()
        .Where(x => x.Coordinates != null && x.Coordinates.Distance(_centerCoordinate) <= _withinDistance);

**Comment by peetw** [comment]
One final suggestion if the above doesn't work - you may be able to use SpatialProjections to avoid the need to buffer the center point (not tested):

    return session.QueryOver<Entity>()
        .Where(x => x.SourcePartner.PartnerId == _sourcePartnerId)
        .And(x => x.Coordinates != null)
        .And(
            Restrictions.Le(
                SpatialProjections.Distance<Entity>(x => x.Coordinates, _withinDistance),
                _centerCoordinate
            )
        )
        .List();
