### ISSUE TITLE
Could you check with a new prelease version GeoAPI and NetTopologySuites version 2?..

### ISSUE THREAD

**Issue by alejandropadillav1** [nhibernate/NHibernate.Spatial#106]
Hi pp

Show in the title message, the GeoAPI and NetTopologySuite are planning to release version to V2.0, currently I am using with a NHibernate.Spatial in order to manage a Spatial Data.

I was testing there with a release version, it throws an exceptions.

Thanks in advance

Regards.

**Comment by peetw** [comment]
@alejandropadillav1 thanks for the heads up. I have updated NTS to 2.0 and fixed any issues. We will release an updated version soon.
