### ISSUE TITLE
Version numbering

### ISSUE THREAD

**Issue by peetw** [nhibernate/NHibernate.Spatial#110]
This is more of a general question than an issue per se.

So far we have tried to keep our version numbers relatively in line with NHibernate's (i.e. we moved to v5.0 when we updated our dependency on NHibernate to v5.0, same with v5.1, etc.).

However, with PR #107, it would probably make sense (assuming we want to follow [semantic versioning](https://semver.org/)) to bump the version number to v5.3.0 (since we're "adding functionality in a backwards compatible manner"). Furthermore, with the current work I have been doing to migrate from NTS v1.x to v2.x (see #106), it would make sense to change the version number to v6.0 (despite there being no v6.0 of NHibernate yet).

So the question is, do we want to follow semantic versioning completely, or do we want to tie our major version number to whatever major version of NHibernate we are currently referencing?

@andrerav @fredericDelaporte I'd be interested to hear your thoughts on this.

**Comment by fredericDelaporte** [comment]
We have the same issue for [NHIbernate.Caches](https://github.com/nhibernate/NHibernate-Caches). Currently, I have decided to keep the major in sync, and update the minor independently. In release notes, the targeted NHibernate is told.
In effect, this forbids breaking changes until NHibernate releases a major. For caches, that is not much an issue.

**Comment by hazzik** [comment]
I think that version should be independent and following sem-ver, so if you need to release a new major version - go for it.

**Comment by peetw** [comment]
Thanks for your comments!

There's also the issue of whether we should continue to version all of the NuGet packages that we release (`NHibernate.Spatial.MsSql`, `NHibernate.Spatial.PostGis`, etc.) as a single "entity" (i.e. they all share the same version) or whether we should start to version them independently. For example, the recent work to port the MsSql package to .NET Standard 2.0 would be a breaking change for consumers, so ideally we would bump the major version; however, there were no changes to any of the other packages, so it seems a bit weird to release a v6.0 of the PostGis package that is exactly the same as the latest v5.2.0 version...

**Comment by hazzik** [comment]
On the case of `NHibernate.Spatial.MsSql` I would do a _new_ package with exact same version as others.

**Comment by fredericDelaporte** [comment]
For caches, I have also had the trouble (but for minor changes), and decided to keep the same version for all. Having different versions would somewhat complicate the release process, and I chose to keep it simple.
Moreover if you have dependencies among your packages, and could end-up quite confusing for user. How would they sort out easily which version is the right one for each package, excepted relying on NuGet to sort it out by itself?
I have on some occasion (third digit change) only released the changed ones, with a note about the other ones having not changed and having not been re-released. But for the next release they have been all released with the same version.

**Comment by andrerav** [comment]
Hi @peetw and others,

As you have pointed out, historically NHibernate.Spatial has been versioned in a manner that usually mirrors NHibernate. NHibernate has had a lot of steady forward momentum with new features and shortcomings and limitations being fixed on a regular basis. Sometimes these changes would lead to incompatibilities with NH.Spatial, so releasing a new version of NHibernate.Spatial was often a direct consequence of upgrading to a newer version of NHibernate. 

And I guess synchronizing the version numbers became a sort of lazy way to help guide the user towards the correct version of NHibernate to use with NH.Spatial. [Dependency version range specifications](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges-and-wildcards) would probably have been a better way to do this :)

Anyway, like @hazzik, I am 100% positive towards your suggestion. We should use semantic versioning. NHibernate.Spatial Version 6.0 sounds great! :)

With regards to NHibernate.Spatial.MsSql, @hazzik's suggestion to create an entirely new package sounds like a fair idea. As for what it should be called -- perhaps _NHibernate.Spatial.MsSql.Standard_ or _NHibernate.Spatial.MsSql.NetStandard_?
