### ISSUE TITLE
Mapping by code sets IGeometry / IGeography database type to small int

### ISSUE THREAD

**Issue by suryapratap** [nhibernate/NHibernate.Spatial#12]
if I have a mapping code like
```C#
mapper.Class<GisPoint>(map => map.Property(col => col.Geom, prp => prp.Type<NHibernate.Spatial.Type.MsSql2008GeometryType>()));
```
and the model like 
```C#
public class GisPoint
	{
                public virtual Guid Id {get; set;}
		
                public virtual double X { get; set; }

		public virtual double Y { get; set; }

		public virtual int SRID { get; set; }

		public virtual IGeometry Geom { get; set; }
     }
```

the database schema automatically generated takes GisPoint.Geom to be a small int.

this is caused if you set configuration like so
```C#
var configuration = new Configuration();
				configuration.DataBaseIntegration(c =>
				{
					c.Dialect<MsSql2012Dialect>();
					c.ConnectionString = connectionString;
					c.KeywordsAutoImport = Hbm2DDLKeyWords.AutoQuote;
					c.SchemaAction = SchemaAutoAction.Update;
				});
```

**Comment by andrerav** [comment]
@suryapratap Can you help me clarify this issue please. I see you are using MsSql2012Dialect and not MsSql2012GeometryDialect, is this intentional?

**Comment by suryapratap** [comment]
It was not intentional, I missed it totally. I will change the dialect and test again.

**Comment by suryapratap** [comment]
I had migrated the project to use PostGisDialect, here the automatic setting sets the column to **text** instead of **geometry**. 

changing dialect to MsSql2012GeometryDialect sets the column to nvarchar(MAX).

**Comment by rungwiroon** [comment]
@suryapratap Try to set column type by SqlType like this.
```c#
Property(g => g.Point, map =>
                {
                    map.Column(cm =>
                    {
                        cm.Name("point");
                        cm.SqlType("geometry");
                    });

                    map.Type<NHibernate.Spatial.Type.GeometryType>(new
                    {
                        srid = 4326,
                        subtype = "POINT"
                    });
                });
```

**Comment by andrerav** [comment]
@rungwiroon: Interesting, could this mean that this is potentially a bug in NHibernate core?

**Comment by peetw** [comment]
Given the following entity class:

    public class Entity
    {
        public virtual Polygon geom { get; set; }
    }

we use the following mapping to generate the correct SQL schema for the PostGis dialect:

    mapping.Map(x => x.geom)
        .CustomType<PostGisGeometryType>()
        .CustomSqlType("geometry(Polygon, 4326)");

(We actually use `CustomSqlType("geometry(Polygon)");` and some regex `Action<string>` with NHibernate's `SchemaUpdate()` method to dynamically insert the SRID into the SQL schema before it is executed against the database, but that's not important for this example).

If the `CustomSqlType` is omitted, then the SQL type is indeed set to **text** (as @suryapratap states).

@andrerav not quite sure what you mean by a bug in NHibernate?

**Comment by suryapratap** [comment]
>  (We actually use CustomSqlType("geometry(Polygon)"); and some regex Action<string> with NHibernate's SchemaUpdate() method to dynamically insert the SRID into the SQL schema before it is executed against the database, but that's not important for this example).

> If the CustomSqlType is omitted, then the SQL type is indeed set to text (as @suryapratap states).

@peetw  ideally  the CustomType and CustomSqlType declarations should not be required since that is part of the task that a database provider should do. What was the need for Regex to insert SRID? what was the default action doing without the Regex?.

**Comment by peetw** [comment]
I'm not sure how you could omit the `CustomType`? How would NHibernate know what to do with a `Polygon` otherwise?

The reason for the regex is that the SRID for our geometry columns is not known until runtime (i.e. our users create the database schema). Without the regex, the mapping looks like this:

    mapping.Map(x => x.geom)
        .CustomType<PostGisGeometryType>()
        .CustomSqlType("geometry(Polygon)");

and whilst this generates "legal" SQL, the SRID defaults to 0 in the PostGis database which is not a valid EPSG SRID and thus the column is fairly unusable in GIS terms.

**Comment by suryapratap** [comment]
What I meant is ```x.geom``` should be able to set the custom type since the PostGIS provider should know what custom type to map with

Is the SRID set during the mapping phase or is it a per entity thing?

**Comment by peetw** [comment]
Ah ok :) By PostGIS provider, do you mean the `PostGisDialect` within NHibernate.Spatial?

For our application, the SRID is only provided by the user when they wish to create/recreate the database schema. In our case, it is applied to all entities; however, in a PostGIS database it is perfectly legal for multiple geometry columns to have different SRIDs.

The SRID is not needed during the mapping phase as it is only used when generating schema SQL (which is true for any arg passed to `CustomSqlType()`).

**Comment by suryapratap** [comment]
The default SRID is being set in the [DB]Type class but the default selector  ```CustomType<>()``` or ```Map()``` does not expose an option to set the default SRID. 

Will it be a good idea to use one of these to set the SRID

**Comment by hazzik** [comment]
You can use CustomType with an instance, instead of generic

**Comment by suryapratap** [comment]
@hazzik yes :) but ```CustomType<T>(Action<T> cfg)``` seemed like a nice to have option

**Comment by hazzik** [comment]
Please create an issue in JIRA:)

**Comment by suryapratap** [comment]
The way I see it, type mapping of the geometry/geography classes is being set by ```GeometryTypeBase<T>``` and the sqlType defined in 

```C#
protected GeometryTypeBase(NullableType nullableType)
        {
            this.nullableType = nullableType;
            this.sqlType = nullableType.SqlType;
        }
```
we need to do something about the ```this.sqlType``` as that is what will be used to create the schema scripts.

**Comment by andrerav** [comment]
I'm looking at a similar problem with the MySQL dialect now. Take a look at this method in SpatialAuxiliaryDatabaseObject:

```
        private void VisitGeometryColumns(Action<Table, Column> visitGeometryColumn)
        {
            // This would be quite illegal, because "configuration" is a private
            // field of Mapping class, the most probable implementation of IMapping.
            //
            //this.configuration = mapping.configuration;

            foreach (PersistentClass persistentClass in this.configuration.ClassMappings)
            {
                Table table = persistentClass.Table;
                foreach (Column column in table.ColumnIterator)
                {
                    if (column.Value.Type.ReturnedClass is IGeometry)
                    {
                        visitGeometryColumn(table, column);
                    }
                }
            }
        }

```                

The field column.Value.Type.ReturnedClass is never IGeometry, and the dialect specific GetSpatialCreateString() method is thus never called.

**Comment by andrerav** [comment]
@suryapratap Can you please confirm if merge #47 fixes this issue?

**Comment by andrerav** [comment]
@suryapratap Disregard that. This problem originates in issue #9 and the changes made to the code there. I will continue the discussion on that issue.

**Comment by andrerav** [comment]
I think we found the cause for this; the geometry columns are generated as tinyints by default -- it's necessary to attach an instance of SpatialAuxiliaryDatabaseObject to the configuration which will automatically generate scripts that modifies the schema with geometry types. This is how it's done:

`configuration.AddAuxiliaryDatabaseObject(new SpatialAuxiliaryDatabaseObject(configuration));`

It's necessary to do this with mapping by code, FluentNHibernate and normal XML mapping.

**Comment by peetw** [comment]
So does this mean that both `CustomType` and `CustomSqlType` can now be omitted from the mapping in the [example I posted](https://github.com/nhibernate/NHibernate.Spatial/issues/12#issuecomment-200327412)?

**Comment by andrerav** [comment]
@peetw: You still need CustomType(), and I believe you can subclass PostGisGeometryType to set a custom SRID in a cleaner manner. Check out this example: https://github.com/nhibernate/NHibernate.Spatial/issues/9#issuecomment-40578831
