### ISSUE TITLE
Geometry exception

### ISSUE THREAD

**Issue by robertovaldesperez** [nhibernate/NHibernate.Spatial#121]
Position = NetTopologySuite.Geometries.Geometry.DefaultFactory.CreatePoint(new Coordinate(w.Longitud, w.Latitud))
Position is a IGeometry. My database have a postgis extension installed.

Exception message:
Stack trace:
```
'Errors' node cannot be resolved for the specified context [Npgsql.NpgsqlException (0x80004005): The NpgsqlDbType 'Geometry' isn't present in your database. You may need to install an extension or upgrade to a newer version.
   en Npgsql.TypeMapping.ConnectorTypeMapper.GetByNpgsqlDbType(NpgsqlDbType npgsqlDbType)
   en Npgsql.NpgsqlParameter.ResolveHandler(ConnectorTypeMapper typeMapper)
   en Npgsql.NpgsqlParameter.Bind(ConnectorTypeMapper typeMapper)
   en Npgsql.NpgsqlCommand.ValidateParameters(ConnectorTypeMapper typeMapper)
   en Npgsql.NpgsqlCommand.<ExecuteReaderAsync>d__102.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Npgsql.NpgsqlCommand.<ExecuteNonQuery>d__92.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Npgsql.NpgsqlCommand.ExecuteNonQuery()
   en NHibernate.AdoNet.AbstractBatcher.ExecuteNonQuery(DbCommand cmd)
   en NHibernate.AdoNet.NonBatchingBatcher.AddToBatch(IExpectation expectation)
   en NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object id, Object[] fields, Boolean[] notNull, Int32 j, SqlCommandInfo sql, Object obj, ISessionImplementor session)].
```

Npgsql version: 4.1.3.1
PostgreSQL version:13
NHibernate 5.2.7
NHibernate.Spatial: 5.3.0
NHibernate.Spatial.PostGis: 5.3.0
Operating system:  Windows 10 x64

**Comment by peetw** [comment]
Hi, please can you run the following query on the database and report the output: `SELECT PostGIS_Full_Version();`

Can you also post the code that is causing the error? Thanks.

**Comment by robertovaldesperez** [comment]
"POSTGIS=""3.0.2 3.0.2"" [EXTENSION] PGSQL=""130"" GEOS=""3.8.1-CAPI-1.13.3"" SFCGAL=""1.3.8"" PROJ=""6.3.2"" GDAL=""GDAL 3.0.4, released 2020/01/28 GDAL_DATA not found"" LIBXML=""2.9.9"" LIBJSON=""0.12"" LIBPROTOBUF=""1.2.1"" WAGYU=""0.4.3 (Internal)"" TOPOLOGY RASTER"

**Comment by peetw** [comment]
Thanks. I see that you are trying to map to a `geography` type column, which may be the issue, although it should be able to cast back and forth, as described [here](http://www.npgsql.org/doc/types/nts.html#geography-geodetic-support). I'm not sure why you've overridden the `SqlTypes` method? I would change the type of the `Position` property on the `CadastralEstate` entity from `IGeometry` to `IPoint` and also change the mapping to:

    Map(x => x.Position).Column("POSITION").CustomSqlType("GEOGRAPHY").CustomType<PostGisGeometryType>().Index("IX_ESTATE_POSITION").Nullable();

I assume you're not using NHibernate to actually create the database schema?

**Comment by robertovaldesperez** [comment]
Yes, I am using NHibernate to create the database schema.

**Comment by robertovaldesperez** [comment]
Any idea?

**Comment by peetw** [comment]
It looks like this is a wider issue relating to the use of Npgsql 4 (see #123). I suggest you try downgrading to Npgsql 3.2.7 and see if that helps

**Comment by robertovaldesperez** [comment]
@peetw hi,

I have tried version 3.2.7 but it does not work, with the only version that worked for me was with 2.2.7, but since I changed to nhibernate 5 this last version is no longer valid for me

**Comment by peetw** [comment]
Hmm OK, I'll have to look into this, but don't have a lot of time at the moment (any pull requests are gladly welcomed though 😃). What was the error message you received with Npgsql 3.2.7?

**Comment by robertovaldesperez** [comment]
I got the same error. Don't worry if you don't have time, I'll wait for it to be fixed if possible. Thank you very much for your time

**Comment by peetw** [comment]
OK thanks. I guess one workaround in the meantime would be to just use a `geometry(Point, 4326)` type column in the database and manually cast it to `geography` in any SQL queries that need to use the geography-specific PostGIS methods. The official PostGIS docs also have info on when to use geometry vs geography: https://postgis.net/docs/using_postgis_dbmanagement.html#PostGIS_GeographyVSGeometry

**Comment by robertovaldesperez** [comment]
hi @peetw  When do you think it can be fixed, more or less?

**Comment by peetw** [comment]
I'm pretty busy with work atm, so I'm not sure - sorry! It might be a while though, so I would probably try and use the recommended workaround if you can. I'm hopeful that resolving the Npgsql 4 issue will also resolve this issue.
