### ISSUE TITLE
Support Npgsql 4

### ISSUE THREAD

**Issue by peetw** [nhibernate/NHibernate.Spatial#123]
Using Npgsql 4.0 or later causes the PostGIS tests to fail with the following message:

> The NpgsqlDbType 'Geometry' isn't present in your database. You may need to install an extension or upgrade to a newer version

This is likely due to the changes introduced in Npgsql 4 in how PostGIS types are handled; see:

- http://www.npgsql.org/doc/types/nts.html
- http://www.npgsql.org/doc/types/legacy-postgis.html

**Comment by eithe** [comment]
@peetw Have you looked at what changes are needed to support npgsql 4.x? It would be great to find a way to upgrade Npgsql due to many performance improvements in later versions of that project.

**Comment by peetw** [comment]
@eithe Not yet unfortunately, work has been super busy recently so haven't had the time! Definitely agree and would certainly welcome any PRs in this area :)
