### ISSUE TITLE
PostGIS 3.1+ support

### ISSUE THREAD

**Issue by peetw** [nhibernate/NHibernate.Spatial#129]
Running the `Tests.NHibernate.Spatial.PostGis20` tests with PostGIS 3.1+ fails with the following error:

    OneTimeSetUp: NHibernate.HibernateException : 42883: function st_intersection(geometry, geometry) does not exist
      ----> Npgsql.PostgresException : 42883: function st_intersection(geometry, geometry) does not exist
    Data:
      Severity: ERROR
      SqlState: 42883
      Code: 42883
      MessageText: function st_intersection(geometry, geometry) does not exist
      File: d:\pginstaller_12.auto\postgres.windows-x64\src\backend\catalog\pg_aggregate.c
      Line: 871
      Routine: lookup_agg_function

**Comment by peetw** [comment]
Seems to be caused by the following SQL statement:

```
CREATE AGGREGATE NHSP_IntersectionAggregate(BASETYPE=GEOMETRY, SFUNC=ST_Intersection, STYPE=GEOMETRY);
```

**Comment by peetw** [comment]
The error is caused by the fact that the signature for `ST_Intersection` changed in PostGIS 3.1 - it now has an optional `gridSize` parameter (see [here](https://postgis.net/docs/release_notes.html#idm43729) and [here](https://postgis.net/docs/ST_Intersection.html)). Therefore, will need to conditionally create a wrapper around the new function depending on the PostGIS version.

**Comment by peetw** [comment]
Fixing the intersection aggregate issue reveals that tests `ConformanceItemT48Hql` and `ConformanceItemT48Linq` are also failing with PostGIS 3.1, but this looks to be due to the ordering of the returned polygon co-ordinates - using `EqualsTopologically` rather than `EqualsExact` resolves the issue

**Comment by andrerav** [comment]
Great work @peetw! 🙏
