### ISSUE TITLE
PostGisDialect property SupportsIdentityColumns should return true

### ISSUE THREAD

**Issue by peetw** [nhibernate/NHibernate.Spatial#23]
Is there any reason why this [property](https://github.com/nhibernate/NHibernate.Spatial/blob/e4e9c34c769f4812f811d2bacc367e66597e355c/NHibernate.Spatial.PostGis/Dialect/PostGisDialect.cs#L61) still returns `false`? Currently this means that FluentNHibernate's automapping maps Id columns using `integer` and a single "hibernate_sequence", rather than mapping them as `serial` with individual sequences for each table...

I'm not sure I understand the xmldoc comments and the TODO item seems to suggest it should have been changed back to returning `true`. I've certainly had success (mappings and schema generation all run fine) using the following derived class:

    public class PostGisModDialect : PostGisDialect
    {
        public override bool SupportsIdentityColumns
        {
            get { return true; }
        }
    }

**Comment by andrerav** [comment]
@peetw: I am confused by the comment as well. This dates back to 2009/2010, so it's hard to tell what was going on. I will try making this modification and see how it impacts the tests.

**Comment by peetw** [comment]
If it's any help, these are the NuGet packages I'm using:

    <?xml version="1.0" encoding="utf-8"?>
    <packages>
      <package id="CommandLineParser" version="1.9.71" targetFramework="net452" />
      <package id="FluentNHibernate" version="2.0.1.0" targetFramework="net452" />
      <package id="GDAL" version="1.10.0.9-a" targetFramework="net452" />
      <package id="GDAL.Native" version="1.10.0.9-a" targetFramework="net452" />
      <package id="GeoAPI" version="1.7.3.1" targetFramework="net452" />
      <package id="Iesi.Collections" version="4.0.1.4000" targetFramework="net452" />
      <package id="NetTopologySuite" version="1.13.3.2" targetFramework="net452" />
      <package id="NetTopologySuite.IO" version="1.13.3.2" targetFramework="net452" />
      <package id="NetTopologySuite.IO.SpatiaLite" version="1.13.3.2" targetFramework="net452" />
      <package id="NHibernate" version="4.0.3.4000" targetFramework="net452" />
      <package id="NHibernate.Spatial" version="2.2.0" targetFramework="net452" />
      <package id="NHibernate.Spatial.PostGis" version="4.0.3.4000" targetFramework="net452" />
      <package id="NLog" version="4.0.1" targetFramework="net452" />
      <package id="Npgsql" version="2.2.5" targetFramework="net452" />
      <package id="System.Data.SQLite.Core" version="1.0.97.0" targetFramework="net452" />
    </packages>

**Comment by keyjote** [comment]
Hi @peetw, do you have any new status of this issue?
I had the same problem and thanks to this post now I am able to save new rows in the db.

**Comment by andrerav** [comment]
@keyjote: I haven't gotten around to this yet, I will fix this very soon and release a new NuGet package :)

**Comment by peetw** [comment]
@keyjote I'm not a contributor - just someone who was in your position when I started ;)

@andrerav I'd be more than happy to submit a pull request fixing this issue - it would be nice to give something back to this project :) I assume it would just be a case of making the switch from `false` to `true` and making sure the tests pass?

**Comment by andrerav** [comment]
@peetw That would be great! And yes, it's a big plus if you ensure that the tests are still passing :)
