### ISSUE TITLE
Registering metadata error

### ISSUE THREAD

**Issue by PostbuzzAndriy** [nhibernate/NHibernate.Spatial#24]
When i do NHibernate.Spatial.Metadata.Metadata.AddMapping( cfg, NHibernate.Spatial.Metadata.MetadataClass.SpatialReferenceSystem ); I get an error
Resource not found: NHibernate.Spatial.Metadata.SpatialReferenceSystem.MsSql2008GeographyDialect.hbm.xml
but looking into the library System.Reflection.Assembly.Load("NHibernate.Spatial.MsSql").GetManifestResourceNames() we can find:
 "NHibernate.Spatial.Metadata.GeometryColumn.MsSql2008GeographyDialect.hbm.xml"
 "NHibernate.Spatial.Metadata.GeometryColumn.MsSql2008GeometryDialect.hbm.xml"
 "NHibernate.Spatial.Metadata.SpatialReferenceSystem.MsSqlLegacyDialect.hbm.xml"
 "NHibernate.Spatial.Metadata.GeometryColumn.MsSqlLegacyDialect.hbm.xml"
Why the logic seeks for missing resource?

package
NHibernate.Spatial.MsSql version="4.0.3.4000"

**Comment by andrerav** [comment]
Hi @PostbuzzAndriy, can you post your configuration and mapping?

**Comment by andrerav** [comment]
I am going to assume this was a user error, feel free to reopen if this problem still persists.

**Comment by moh-abed** [comment]
I have the same issue 
I am using the following dialect:
<property name="dialect">NHibernate.Spatial.Dialect.MsSql2012GeographyDialect,NHibernate.Spatial.MsSql</property>


And got the error:
Hibernate.MappingException : Resource not found: NHibernate.Spatial.Metadata.GeometryColumn.MsSql2012GeographyDialect.hbm.xml
   at NHibernate.Cfg.Configuration.LogAndThrow(Exception exception)
   at NHibernate.Cfg.Configuration.AddResource(String path, Assembly assembly)
