### ISSUE TITLE
Update NuGet package from 2.2.0 to 4.0.3.4000

### ISSUE THREAD

**Issue by peetw** [nhibernate/NHibernate.Spatial#25]
Currently the NuGet package for [NHibernate.Spatial](https://www.nuget.org/packages/NHibernate.Spatial/) is stuck on version 2.2.0, whereas the sub-packages ([MsSql](https://www.nuget.org/packages/NHibernate.Spatial.MsSql/), [PostGis](https://www.nuget.org/packages/NHibernate.Spatial.PostGis/), etc.) are all on version 4.0.3.400. Is there any reason for this?

It means that in order to use NHibernate.Spatial functionality introduced since 2.2.0, you have to reference one of the sub-packages, even if you do not need any of the specific functionality from that sub-package.

**Comment by andrerav** [comment]
Hi,

The package you refer to is a very old version of NHibernate.Spatial built
for NHibernate 2.2 and is not associated with this project and is not a
dependency for the packages produced by this project.

-Andreas

**Comment by peetw** [comment]
Thanks for the quick response :)

Indeed. What I was thinking was whether it would be possible to update the package (based on the NHibernate.Spatial project in this repo) so that the base functionality can be included without having to install a database-specific sub-package?

**Comment by peetw** [comment]
For example, in one of my current applications, I have 2 projects: A and B. Project A references project B, which performs all the database management and references NHibernate.Spatial.MsSql, NHibernate.Spatial.PostGis, etc. Project A performs some spatial query so in theory it only needs to reference NHibernate.Spatial since the actual handling will be done by the appropriate database-specific DLLs which are already included via project B. However, since the current version of NHibernate.Spatial on NuGet is too low, it has to reference one of the database-specific packages, even though it's not used directly...

I've tried to contact the current owner of the NuGet package (wandelson), but I've not had any response, do you know if they're still active?

**Comment by andrerav** [comment]
@peetw Well I suppose I could create a separate NuGet package for NHibernate.Spatial (even though on NuGet it would have to be named something else, like NHibernate.Spatial.Base). However I am reluctant to make that a dependency for the various dialect flavors. Could this solution work for you?

**Comment by peetw** [comment]
@andrerav That sounds like it would work, but only if the dialect flavours also used the updated package as their dependency, otherwise you would end up with 2 versions of NHibernate.Spatial in the solution (v2.2 from the dialect dependency; v4.x from NHibernate.Spatial.Base). What would need to be done to update the dialects to use the updated NHibernate.Spatial.Base?

**Comment by andrerav** [comment]
@peetw Solution 1:
1. Create a NuGet package from NHibernate.Spatial (NHibernate.Spatial.Base)
2. Remove the dependency on NHibernate.Spatial from the various dialects
3. Add a new dependency on the NuGet package to the various dialects

Solution 2: (if it is possible)
1. Same as solution 1
2. Keep the internal dependency structure in the solution
3. Add a dependency on the NHibernate.Spatial.Base package when creating packages for the various dialects, and make sure that NHibernate.Spatial.dll is not included in the various dialect packages.

Solution 2 is favourable, but I don't know if it's possible (specifically step 3). Solution 1 would be way too cumbersome in bugtracking/debugging scenarios.

**Comment by peetw** [comment]
Surely solution 1 would be the cleanest way of doing it? Unless I've misunderstood (very possible :D), it's how it works at the moment, so I don't see why it would add to the maintenance overhead? If anything, using an active NuGet package that you control (NHibernate.Spatial.Base) as a dependency, rather than a dead package (NHibernate.Spatial), should make maintenance easier?

**Comment by andrerav** [comment]
@peetw I think you may have misunderstood the relationship between this project and the NHibernate.Spatial NuGet package. The NHibernate.Spatial package is built for NHibernate 2.2 and is not associated with this project and is not a dependency for any of the packages produced by this project.

Creating an internal NuGet dependency on the hypothetical NHibernate.Spatial.Base would make debugging very cumbersome, so it's not a realistic alternative.

For example, the workflow would be something like:
1. Bug reported
2. Implement possible fix in NHibernate.Spatial.Base
3. Build and publish package to NuGet
4. Wait 10 min for the package to be indexed
5. Update packages in say NHibernate.Spatial.MsSql
6. Test fix.
7. Goto 2.

I'm pretty sure I'm not gonna walk into that willingly :)

**Comment by hazzik** [comment]
@nhibernate/nhibernate-spatial try to contact owner of NHibernate.Spatial package first. Sometimes it does help

**Comment by andrerav** [comment]
@hazzik Yes, we will absolutely do that if we decide to move on to split out a separate package for NHibernate.Spatial :)

**Comment by peetw** [comment]
@andrerav I understand that ;) But this project does build a NHibernate.Spatial DLL that is currently at the same version as the dialects (v4.x) and is included as a dependency when referencing the dialect NuGet packages, no? My thoughts were that this DLL could be moved to its own NuGet package, so that it could be referenced independently of the dialects. However, I see now that this would increase your workload :( Although I'm not sure why you'd have to publish the package to test it, rather than testing it locally (forgive my lack of knowledge here, I have not created any NuGet packages yet).

@hazzik Yeah, I tried contacting them in the first instance (August), but have not heard anything back...

**Comment by andrerav** [comment]
@peetw That's what my proposed solution #2 seeks to amend. If it is possible to maintain a regular project reference within the solution while still being able to publish two different NuGet packages then everything is peachy. I need to read up on NuGet to figure out how to do that though, if it is even possible. I do know that it is possible to forcibly remove a dependency from a package, but I don't know if it is possible to forcibly add a dependency and also remove an assembly. NuGet is pretty flexible so I'm guessing it's possible. This is hardly an uncommon challenge in projects like this.

**Comment by peetw** [comment]
@andrerav Ok great :) Let me know if you need a hand testing anything!

Also, just for my (and anyone else viewing this!) future reference, I highlighted the DLL in question:

![image](https://cloud.githubusercontent.com/assets/1334162/11179616/97411cf0-8c4c-11e5-8c16-3d67e148bb23.png)

**Comment by andrerav** [comment]
@peetw I did some checking, and it seems that it is possible to realize this without jumping through any hoops. Currently we use the -IncludeReferencedProjects to actually include the NHibernate.Spatial.dll assembly, so this can simply be removed. To set up the correct dependency structure it is probably necessary to start using .nuspec files, but it's about time we started doing that anyway.

I will contact the maintainer of the NHibernate.Spatial package and ask if it's possible to get a co-admin permission on that package. If I don't get a reply in a reasonable amount of time I will default to NHibernate.Spatial.Base as package name unless anyone else has better suggestions.

**Comment by peetw** [comment]
That's good news :) Hopefully you'll hear back from NHibernate.Spatial!

**Comment by peetw** [comment]
Also, I suppose we may be able to contact the NuGet Gallery Support team if the NHibernate.Spatial package really is dead. Or at least this is what is recommended in the [FAQs](http://docs.nuget.org/consume/nuget-faq#managing-packages-in-nuget.org):

> If you feel that an existing package has taken the name which suits your package more, try contacting the owner of the package. If you didnt get response within a couple of weeks, you can contact support and the NuGet Gallery team will look in to it.

**Comment by andrerav** [comment]
@peetw I don't think that will be necessary, the package name isn't really that important and the maintainer created his package with good intentions. If he gets back to me then great, otherwise it's really no problem.

**Comment by peetw** [comment]
Just wondering what the status is atm? I'm guessing you've not heard back from the old package maintainer? Let me know if there's anything I can do to help :)

**Comment by andrerav** [comment]
That's correct, I never heard back from the package maintainer. I haven't investigated how well this will work within the solution either.

**Comment by suryapratap** [comment]
Closing this as this does not affect the current packages.
