### ISSUE TITLE
MsSql2008FunctionRegistration.GetSpatialCreateString fails to recognize when a geometry-column is not nullable.

### ISSUE THREAD

**Issue by danielcweber** [nhibernate/NHibernate.Spatial#26]
Not sure whether MsSql2008FunctionRegistration is the exact class for setting "NOT NULL" constraints for geometry/geography-type columns on MS-SQL-Server, however, somewhere in the processing chain, this information is lost.

**Comment by andrerav** [comment]
Hi @danielcweber,

Can you please tell us more about your environment and how you are triggering this behaviour?

Thanks,
Andreas

**Comment by danielcweber** [comment]
I created a minimal working example [here](https://github.com/danielcweber/NHibernateSpatialBug).
Note that you need to set a valid connection string.

The desired behavior would create a not-null geography column named "Area" in a table named "SomeAreaClass". The actual behaviour fails to add the constraint.

I guess this should be set [here](https://github.com/nhibernate/NHibernate.Spatial/blob/e4e9c34c769f4812f811d2bacc367e66597e355c/NHibernate.Spatial.MsSql/Dialect/MsSql2008FunctionRegistration.cs#L560), however, it seems that the function does not even get the necessary information.

**Comment by danielcweber** [comment]
Any news on this ?

**Comment by andrerav** [comment]
Hi @danielcweber, I haven't gotten around to trying out your example yet, sorry about that! I will try to take a look at this next week :) Your example is great and will allow me to debug exactly what is going on. Sorry for taking so long!

**Comment by andrerav** [comment]
Okay so curiosity got the better of me, seems this is pretty straight forward fix, but I will need to alter the ISpatialDialect interface to achieve this. The information required to correctly configure nullability is available a bit earlier in the [call stack](https://github.com/nhibernate/NHibernate.Spatial/blob/e4e9c34c769f4812f811d2bacc367e66597e355c/NHibernate.Spatial/Mapping/SpatialAuxiliaryDatabaseObject.cs#L152).

**Comment by andrerav** [comment]
This issue affects PostGis and MySQL dialects too. I have committed a fix: https://github.com/nhibernate/NHibernate.Spatial/commit/a72c6f56bfaefb048d5bd1b00fe9da07b3ee60f1

NuGet packages will follow once I have tested the MySQL and PostGIS changes thoroughly.
