### ISSUE TITLE
Dependency to Microsoft.SqlServer.Types should probably be removed from the NHibernate.Spatial.MsSql nuget package.

### ISSUE THREAD

**Issue by andrerav** [nhibernate/NHibernate.Spatial#27]
The reference to Microsoft.SqlServer.Types has proven to be quite annoying due to the manner in which it installs binaries and source code which is completely redundant in projects where deployment of these binaries are handled manually (which is a much better practice). This dependency should be removed from the NuGet package unless there are very good reasons to keep it.

**Comment by suryapratap** [comment]
:+1:

**Comment by andrerav** [comment]
Fixed and pushed to NuGet.
