### ISSUE TITLE
OptimisticLock not working with geotype

### ISSUE THREAD

**Issue by EnemyArea** [nhibernate/NHibernate.Spatial#28]
Hi,

we found an issue that currently blocks us very hard. We want to activate nhibernates OptimisticLock feature.

```
        this.OptimisticLock.Dirty();
        this.Version(x => x.ModificationTime).Column("MT").Generated.Always();
```

but I we changed an entity with a geotype it generates sql like

declare @p3 sys.geography
set @p3=convert(sys.geography,0xE61000000114159DAF9215EC4A40F19888688E4725400297DD170AEC4A405BA7C51B92472540)
declare @p5 sys.geography
set @p5=convert(sys.geography,0xE6100000011469248B700CEC4A405BA745E98F4725400297DD170AEC4A405BA7C51B92472540)
exec sp_executesql N'SELECT \* FROM LineObjects WHERE ID = @p1 AND PointCloud = @p2',N'@p0 [geography],@p1 int,@p2 [geography]',@p0=@p3,@p1=1822,@p2=@p5

which is followed by that error:
Invalid operator for data type. Operator equals equal to, type equals geometry
you must use the geography equals function: https://msdn.microsoft.com/en-us/library/bb933809.aspx (STEquals) then it works...

**Comment by andrerav** [comment]
Hi @EnemyArea, that looks like a nasty bug. Is it possible for you to provide a simple solution which showcases this problem?

**Comment by andrerav** [comment]
Hi @EnemyArea, can you please provide your entity and mapping configuration as well as the HQL/LINQ/etc you are trying to execute?

**Comment by peetw** [comment]
Hard to tell what the actual issue is here, especially without a reproducible example. @EnemyArea I assume you either resolved the issue or it's no longer a problem?

**Comment by peetw** [comment]
Closing due to lack of response from OP
