### ISSUE TITLE
Readme file links point to non existing pages

### ISSUE THREAD

**Issue by keyjote** [nhibernate/NHibernate.Spatial#29]
Hi

I have been trying to setup nhibernate spatial for the past days with little luck.
The help links in the readme file for the configuration and mapping don't point to any existing page.
So I had to google and found a really old page (2009) [http://nhibernate.info/doc/spatial/configuration-and-mapping.html] but with those settings I was not able to have it running. I get null on my geometry property.

Any help/links to help me get started would be really appreciated.

**Comment by semone** [comment]
I think the helplink in the readme is the same as the one you linked, at least it seams so looking at this [http://web.archive.org/web/20140803110534/http://nhforge.org/wikis/spatial/configuration-and-mapping.aspx](http://web.archive.org/web/20140803110534/http://nhforge.org/wikis/spatial/configuration-and-mapping.aspx)

**Comment by andrerav** [comment]
Hi,
The old documentation is outdated. Pedro Sousa has written a thorough walkthrough on how to configure and use NHibernate.Spatial. Part 1 starts here: http://build-failed.blogspot.no/2012/02/nhibernate-spatial-part-1.html

**Comment by keyjote** [comment]
Thanks @semone and @andrerav 
I followed the guide from Pedro Sousa and besides a couple of minor things, most of it was the same.
Anyway I followed everything Pedro said and I still got null.

So now I am printing all the logs from nhibernate and found a couple of interesting things:
1) when nhibernate does the select to get the geometry, the geom field is in the query but the set from that column to the Geom property is never done (even though all the other properties for that instance are being called).
2) looking when the propety Geom is being mapped I see this:
WARN  NHibernate.Type.CustomType [(null)] - the custom type 'GeoAPI.Geometries.IGeometry' handled by 'NHibernate.Spatial.Type.PostGisGeometryType' is not Serializable: 
DEBUG NHibernate.Cfg.XmlHbmBinding.Binder [(null)] - Mapped property: Geom -> geom, type: PostGisGeometryType

so this might actually be the problem. But then I am not sure how to solve it or go around it. I tried to create a new method similar to PostGisGeometryType which does not use IGeometry from GeoAPI but that also means I would have to create a new GeometryTypeBase<T> so it uses the correct ToGeometry method.

All this might be possible (and will try it tomorrow), but then again, wouldn't that mean that PostGisGeometryType doesn't really work? Or is it simply that I am missing some simple setting somewhere?

**Comment by peetw** [comment]
Hi, without seeing what you've tried so far, it's hard to comment. However, I've been using NHibernate.Spatial with PostGIS for a good while now and it's all working fine. The entities are mapped via convention, rather than mapping classes, but essentially the mapping boils down to:

`Map(x => x.Geom).CustomType<PostGisGeometryType>().CustomSqlType("geometry(Polygon)");`

where Geom is a member on the entity and is of type `NetTopologySuite.Geometries.Polygon`. UserType conventions are used to ensure that the correct CustomSqlType is used for other geometries, such as LineStrings, etc.

Hope that helps!

**Comment by keyjote** [comment]
Hi @peetw, so you can read my setup here in a question I created in [Stackoverflow](http://stackoverflow.com/questions/35115646/nhibernate-postgres-spatial-geometry-type-become-null) where I described my problem but got no answers :(

Because of your comment I just tried replacing my entity property type to be:
        `public virtual Polygon Geom { get; set; }`
rather than
        `public virtual IGeometry Geom { get; set; }`

but still I get null as the value for Geom.
I also get this in the logs file:

`2016-02-15 20:41:18,732 [339] DEBUG NHibernate.Type.StringClobType [(null)] - returning null as column: geom22_0_`

Maybe by looking at the question you might see something I am forgetting.

Thank

**Comment by keyjote** [comment]
So it ended up that my settings were correct just that the version of Npgsql which I was using (3.0.5) is not compatible with Geometries.
By downgrading Npgsql to version 2.2.7 it did the trick and I was able to get the geometries as expected.

When testing most of the time seems to work, but for large geometries I got an exception:
```
2016-02-17 18:19:15,645 [40] WARN  NHibernate.Util.ADOExceptionReporter [(null)] - System.OutOfMemoryException: Array dimensions exceeded supported range.
   at NHibernate.Spatial.Type.PostGisGeometryType.ToString(Byte[] bytes)
   at NHibernate.Spatial.Type.GeometryTypeBase`1.DeepCopy(Object value)
   at NHibernate.Type.TypeHelper.DeepCopy(Object[] values, IType[] types, Boolean[] copy, Object[] target, ISessionImplementor session)
   at NHibernate.Engine.TwoPhaseLoad.InitializeEntity(Object entity, Boolean readOnly, ISessionImplementor session, PreLoadEvent preLoadEvent, PostLoadEvent postLoadEvent)
   at NHibernate.Loader.Loader.InitializeEntitiesAndCollections(IList hydratedObjects, Object resultSetId, ISessionImplementor session, Boolean readOnly)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.LoadCollection(ISessionImplementor session, Object id, IType type)
```

I will create a different ticket regarding this issue, but I am not sure if I should close this issue as the links in the readme page still point to the wrong place. I still believe the links should be updated either to the old page I mention or redirect them to the tutorial @andrerav pointed out ([link](http://build-failed.blogspot.no/2012/02/nhibernate-spatial-part-1.html))

**Comment by andrerav** [comment]
Thanks @keyjote, links in Readme.md have been updated.
