### ISSUE TITLE
SQL Server 2012 Dialect

### ISSUE THREAD

**Issue by casualtrash** [nhibernate/NHibernate.Spatial#3]
Hello

Would you upgrade the project and add also a new version for the SQL Server 2012 dialect?

**Comment by andrerav** [comment]
SQL Server 2012 support has been implemented. To specify which version of the Microsoft.SqlServer.Types should be used at runtime, specify **Type System Version** in the connection string, as so: 

    server=localhost;database=MyDB;**Type System Version**=SQL Server 2012
