### ISSUE TITLE
PostGIS dialect doesn't support PostGIS 2.x

### ISSUE THREAD

**Issue by peetw** [nhibernate/NHibernate.Spatial#32]
When [registering the spatial functions](https://github.com/nhibernate/NHibernate.Spatial/blob/master/NHibernate.Spatial.PostGis/Dialect/PostGisDialect.cs#L107), the PostGIS dialect does not add the ISO prefix "ST_". This prefix was present for some functions prior to PostGIS v1.5, but was added to all of them in 1.5. At the same time, the non-prefixed ones were deprecated, with the view that they would be removed at a later date ([link](http://postgis.net/docs/manual-1.5/reference.html)):

> PostGIS has begun a transition from the existing naming convention to an SQL-MM-centric convention. As a result, most of the functions that you know and love have been renamed using the standard spatial type (ST) prefix. Previous functions are still available, though are not listed in this document where updated functions are equivalent. The non ST_ functions not listed in this documentation are deprecated and will be removed in a future release so **STOP USING THEM**.

When PostGIS v2.0 was released, they were indeed removed ([link](http://postgis.net/docs/PostGIS_Special_Functions_Index.html#NewFunctions_2_0_Changed)):

> Most deprecated functions have been removed. These are functions that haven't been documented since 1.2 or some internal functions that were never documented. If you are using a function that you don't see documented, it's probably deprecated, about to be deprecated, or internal and should be avoided. If you have applications or tools that rely on deprecated functions, please refer to Q: 3.2 for more details.

The reason I discovered this was that nearly all of the PostGIS tests were failing using PostgreSQL 9.4 x64 and PostGIS 2.1. Is this a known issue? 

In order to support PostGIS 2.x, I added the prefix to those functions (I'll be submitting a pull request shortly). However, what this means is that the minimum version of PostGIS supported would change to 1.5 (1.4 may still be somewhat supported as some of the functions already had the ST prefix in that version - would need further testing). However, given that 1.5 is six years old now, I don't think that's too unreasonable. Thoughts?

**Comment by suryapratap** [comment]
I am wondering if we should version the dialects rather than support only one dialect.

**Comment by andrerav** [comment]
I agree, we're already doing that for SQL Server, and in this case it seems to be a simple thing to implement with inheritance.

**Comment by peetw** [comment]
Good idea, I'll update the pull request when I get a chance.

**Comment by andrerav** [comment]
@peetw that would be great!

**Comment by peetw** [comment]
Is there any preference for naming the dialects? My current thinking is PostGis1Dialect and PostGis2Dialect, but that doesn't really feel right.

Also, what would be the best way to avoid breaking existing code that relies on PostGisDialect? If we move to numbered PostGIS dialects, I don't think there'll be a need for the non-numbered PostGisDialect class.

**Comment by andrerav** [comment]
@peetw Yes, please keep the PostGisDialect as-is and name the new dialect something like PostGis20Dialect or PostGis2Dialect :)

**Comment by peetw** [comment]
@andrerav @suryapratap I've updated the PR if you want to give it a quick check :) Work has been pretty hectic so took a bit longer than I'd expected to get around to it ha

**Comment by andrerav** [comment]
Great work @peetw! I merged the pull request now.
