### ISSUE TITLE
Discussion forum for NHibernate.Spatial

### ISSUE THREAD

**Issue by andrerav** [nhibernate/NHibernate.Spatial#38]
Hi everyone,

I am delighted to see so much activity and progress being made on this project these days! I would like to propose that we create a discussion forum where we can discuss further development without the constraints of creating issues.

Some alternatives off the top of my head:
- Google Groups
- Discourse
- Gitter
- Slack

Suggestions and ideas are very welcome. I will close this issue when we have settled on an appropriate discussion platform.

**Comment by peetw** [comment]
I was thinking this just the other day :) It would be particularly helpful also for people who are thinking of contributing, but who might not be sure.

I'm thinking Discourse might be the best out of those listed above, given it has better support for markdown formatting, etc. than Google Groups. It's also more "forum-like" than the Gitter and Slack messaging platforms (I think??). Not used those chat apps much - we just use Skype at work :(

**Comment by andrerav** [comment]
Discourse looks nice, but it seems this project does not qualify -- we need at least 2000 stars to qualify :(

**Comment by suryapratap** [comment]
Any free group messaging is fine. 

Personally I find email a better solution for this since the mail client will have its own filtering and indexing and can be composed offline without hassle. 

 :+1: Google Groups

**Comment by andrerav** [comment]
Seems we have settled for Google Groups for now. Here is the group: https://groups.google.com/forum/#!forum/nhibernate-spatial

See you there!
