### ISSUE TITLE
MsSql2012SpatialDialect needs a test project

### ISSUE THREAD

**Issue by andrerav** [nhibernate/NHibernate.Spatial#52]
To make both 2008 and 2012 easily testable on a single 2012/2014 server instance, these dialects need different test projects.

**Comment by peetw** [comment]
Does the `Tests.Nhibernate.Spatial.MsSqlSpatial` not already cover it? See [this comment](https://github.com/nhibernate/NHibernate.Spatial/issues/70#issuecomment-309475788). Or have I got things mixed up?

**Comment by peetw** [comment]
Well, it looks like I have indeed got things mixed up :grimacing: It appears that the `MsSqlSpatial` test project and `MsSqlLegacyDialect` are based on the [MsSqlSpatial](http://mssqlspatial.codeplex.com/) extension for MS SQL 2005 databases, written by none other than Ricardo Stuven.

Whether we keep this legacy dialect is another matter....
