### ISSUE TITLE
SpatiaLite Dialect

### ISSUE THREAD

**Issue by andrerav** [nhibernate/NHibernate.Spatial#56]
It may be possible to continue @FObermaier's work on the Spatialite dialect as mentioned by @peetw in https://github.com/nhibernate/NHibernate.Spatial/issues/5. What needs to be done is to fork the Spatialite dialect and bring it up to speed with upstream, and then submit a pull request in a separate branch which @peetw can fork and improve further.

**Comment by peetw** [comment]
I'll try and look into this ASAP :) A (very) minor point though - it tends to be referred to as SpatiaLite rather than Spatialite. Not sure if you want to bother renaming the branch ha.

**Comment by andrerav** [comment]
Hehe :) I removed the branch and created a new one that follows the common feat/#/name pattern (feat/56/SpatiaLiteDialect).
