### ISSUE TITLE
Support for Sql Server 2012 Spatial Dialect

### ISSUE THREAD

**Issue by suryapratap** [nhibernate/NHibernate.Spatial#6]
Just to bring in the context from the emails 

**Stephen Bohlen**

>>One suggestion re: the .MsSql2008 package...when you get to the pt where the package goes GA (e.g., "non-pre") I wonder whether it might be a good idea to add to the descr. of that package that the 2008 package supports SQL Server's Spatial extensions up through SQL Server 2012 (?).  I'm thinking that a consumer of that package would otherwise have no way of knowing that it supported other that SQL Server 2008 (short of perhaps reading release notes which usually aren't visible until after the package is installed).
>>
>>Right now, the description of all three packages is identical:
>>
>>    NHibernate.Spatial is a library of spatial extensions for NHibernate, and allows you to connect NHibernate to a spatially enabled database and manipulate geometries in HQL or in .NET code using NetTopologySuite, providing you with a fully integrated GIS programming experience.
>>
>>If you add to the description something along the lines of ....
>>
>>    This package supports <insert database name here> versions <lowest-version> to <highest-version>.
>>
>>...it might help make things clearer.
>>
>>Now that I think about it, I guess a related question that comes to mind is this:  how would a consumer of these packages for MySQL or PostGIS know what version(s) of those DBs are supported either?  Should there be an e.g., .MySql5 suffix considered for the MySql package?
>>
>>Once you set a package name in NuGet, that's an irreversible decision (at least in re: users updating to the newer packages via NuGet tooling), so we should probably make sure we're using a naming convention that makes coherent sense across packages before these are released for GA.  Since few users (in my experience) do much reading about a package beyond inspecting its name in the NuGet dialog, the name is the first, best opportunity to 'advertise' the package's intent to consumers.
>>
>>What are other's thoughts on this --?  

**Surya Pratap**

>>Yes,
>>we did think of pushing SqlServer2012 as a separate package.
>>
>>but that is just talk right now.
>>
>>I am not sure what will be good, a per-vendor-per-version packages for the db's or just a per-vendor package
>>
>>The first option puts in a lot of dependencies as soon as the vendors release new versions, later a lot of code migration will need to be done if we start depreciating older packages. But this will allow the user to upgrade selectively. One of the reasons for thinking of Sql2008 and Sql2012 is that the spatial dll's for the drivers have changed between versions. I am not sure about the case for other databases.
>>
>>The second option will force users to upgrade db specific dll even if they are still using an older db version (which might not be as bad as it sounds) but it will allow deployment with fewer dependent dll's and easier maintenance.
>>
>>All suggestions are welcome, contributors even more so ;)

**Andreas Ravnestad**

>> Hi!
>> 
>> I have thought some more about adding support for SQL Server 2012. I think one of the most important missing feature is the spatial aggregates which became available in 2012. These are:
>> 
>> -  CollectionAggregate
>> 
>> -  ConvexHullAggregate
>> 
>> - EnvelopeAggregate
>> 
>> - UnionAggregate
>> 
>> These are available for both Geometry and Geography.
>> 
>> In ISpatialDialect.cs the following method interface is defined: SqlString GetSpatialAggregateString(object geometry, SpatialAggregate aggregate);
>> 
>> Currently this method throws a “NotImplementedException” in the MsSql2008 dialect.
>> 
>> I am thinking that a good start may be to create a new MsSql2012SpatialDialect which subclasses the MsSql2008SpatialDialect and overrides this method and returns the proper aggregate string.
>> 
>> I am not sure whether this should be done in a new project or if the MsSql2008 module should be renamed and support multiple dialects. What do you think?

**Comment by andrerav** [comment]
NTS is still waiting for JTS to implement support for circular arcs. Until NTS supports circular arcs, we have no way of supporting them either. If need arises, we can implement the new interfaces and throw NotImplementedException on methods that we can not implement yet. Closing this issue for now.
