### ISSUE TITLE
Implement Criteria SpatialRestrictions.IsWithinDistance

### ISSUE THREAD

**Issue by andrerav** [nhibernate/NHibernate.Spatial#61]
This issue was raised 6 years ago and still seems to be unresolved: http://stackoverflow.com/questions/2427548/criteria-spatialrestrictions-iswithindistance-nhibernate-spatial

One possible solution is given in the link above.

**Comment by dmitrynovik** [comment]
any workaround? I merely want to compute distance between 2 points

**Comment by suryapratap** [comment]
Just one observation here
```C#
 public static SpatialRelationCriterion EqExact(string propertyName, object anotherGeometry, double tolerance)
        {
            // TODO: Implement
            throw new NotImplementedException();
        }


public static SpatialRelationCriterion Relate(string propertyName, object anotherGeometry, string intersectionPatternMatrix)
        {
            // TODO: Implement
            throw new NotImplementedException();
        }

public static SpatialRelationCriterion IsWithinDistance(string propertyName, object anotherGeometry, double distance)
        {
            // TODO: Implement
            throw new NotImplementedException();
        }
```

these are 3 methods that require a similar pattern for the solution
all these methods require one more variable to be held by the ```SpatialRelationCriterion ```
What I would suggest is something more like
```C#
public class SpatialRelationCriterion <T> : SpatialRelationCriterion 
{
	static Dictionary<SpatialRelation,string> filterBuilder = new Dictionary<SpatialRelation,string>
	{
		{SpatialRelation.IsWithihinDistance," < "}
		.
		.
		.
		.
		.
	}
	
	
	private T filterValue;
	internal SpatialRelationCriterion(string propertyName, SpatialRelation relation, object anotherGeometry, T filterValue)
	:base(propertyName, relation, anotherGeometry)
	{
		this.filterValue = filterValue;
	}
	
	public SqlString GetSpatialRelationString(object geometry, SpatialRelation relation, object anotherGeometry, T filterValue)
	{
		var x = new SqlStringBuilder(8)
					   .AddObject(geometry)
					   .Add(".ST")
					   .Add(relation.ToString())
					   .Add("(")
					   .AddObject(anotherGeometry)
					   .Add(")")
					   .Add(filterBuilder[relation])
					   .Add(filterValue.ToString());
		return x.ToSqlString();
	}
}
```

**Comment by suryapratap** [comment]
One other concern is that using the distance relation is not an indexed query a better solution might be to use a buffer with intersect

**Comment by suryapratap** [comment]
> any workaround? I merely want to compute distance between 2 points
Distance function should work without issue AFAIK, this issue is about search within a bounding distance

**Comment by dmitrynovik** [comment]
Yes, there is. Use IGeometry.Distance(IGeometry g)

**Comment by peetw** [comment]
@suryapratap Regarding indexed queries: For PostGIS, the function to use would be `ST_DWithin()` as this can use an index, whereas `ST_Distance()` cannot (see [here](http://postgis.net/2013/08/26/tip_ST_DWithin/) - note that they also specifically recommend against using buffer with intersect).

**Comment by suryapratap** [comment]
@peetw PostGis has ST_DWithin hence the recommendation against the buffer + intersection, issue comes with implementation in SQL Server where a similar function is not there. the buffer + intersection seems like a better choice (in SQL Server) compared to the distance check against all geometries in the column.

**Comment by peetw** [comment]
@suryapratap Indeed, I should probably have said that I was just mentioning the PostGIS-specific version :) I agree that buffer + intersects is probably the way to go for other providers (would need testing though to ensure it is accurate enough for both geometry and geography types).

**Comment by danghuynhdaty** [comment]
This issue has been fixed in `NHibrnate.Spatial` version 5.0.0, hasn't it?

**Comment by peetw** [comment]
@danghuynhdaty not to my knowledge.

**Comment by danghuynhdaty** [comment]
@andrerav can you help me implement for postgis 20, sql2012 and mysql?

**Comment by marcdrexel** [comment]
implemented a work around hope this helps somebody, basically i create my own search circle and then use the working Intersects call. also this work-a-round uses ED50 (europe) for transformations, use NAD83 if you're US based or search for your region at https://epsg.io/ 

requires https://www.nuget.org/packages/ProjNET4GeoAPI/

`using GeoAPI.Geometries;
using NetTopologySuite.Geometries;
using NHibernate.Spatial.Criterion;
using ProjNet;
using ProjNet.CoordinateSystems;
using ProjNet.CoordinateSystems.Transformations;
using System.Collections.Generic;

namespace NHibernate.MyApp.Criterion
{
    public class MySpatialRestrictions 
    {
        public static SpatialRelationCriterion IsWithinDistance(string propertyName, IPoint point, double distance)
        {
            // converts from GPS coords to ED50 (metric), creates our search radius and converts back to GPS (WGS84)
            // dont call buffer on IPoint as long as its GPS/WGS84, you wont get a radius in meters but in degrees 
            var projectedPointToED50 = point.ProjectTo(4326, 2855);
            IGeometry searchAreaED50 = projectedPointToED50.Buffer(distance);  

            var searchAreaWGS84 = searchAreaED50.ProjectTo(2855, 4326);
            searchAreaWGS84 = searchAreaWGS84.Normalized().Reverse(); // reverse for SQL Server

            return SpatialRestrictions.Intersects(propertyName, searchAreaWGS84);
        }
    }

    internal static class GeometryExtensions
    {
        private static CoordinateSystemFactory coordinateSystemFactory = new ProjNet.CoordinateSystems.CoordinateSystemFactory();
        private static CoordinateTransformationFactory coordinateTransformationFactory = new ProjNet.CoordinateSystems.Transformations.CoordinateTransformationFactory();

        private static readonly CoordinateSystemServices _coordinateSystemServices
            = new CoordinateSystemServices(coordinateSystemFactory, coordinateTransformationFactory,
                new Dictionary<int, string>
                {
                    // GPS
                    [4326] = GeographicCoordinateSystem.WGS84.WKT,

                    // Europe Meters https://epsg.io/4230
                    [4230] = @"GEOGCS[""ED50"",
                                DATUM[""European_Datum_1950"",
                                    SPHEROID[""International 1924"",6378388,297,
                                        AUTHORITY[""EPSG"",""7022""]],
                                    TOWGS84[-87,-98,-121,0,0,0,0],
                                    AUTHORITY[""EPSG"",""6230""]],
                                PRIMEM[""Greenwich"",0,
                                    AUTHORITY[""EPSG"",""8901""]],
                                UNIT[""degree"",0.0174532925199433,
                                    AUTHORITY[""EPSG"",""9122""]],
                                AUTHORITY[""EPSG"",""4230""]]",

                    // US meters https://epsg.io/2855
                    [2855] =
                        @"
                    PROJCS[""NAD83(HARN) / Washington North"",
                        GEOGCS[""NAD83(HARN)"",
                            DATUM[""NAD83_High_Accuracy_Regional_Network"",
                                SPHEROID[""GRS 1980"",6378137,298.257222101,
                                    AUTHORITY[""EPSG"",""7019""]],
                                AUTHORITY[""EPSG"",""6152""]],
                            PRIMEM[""Greenwich"",0,
                                AUTHORITY[""EPSG"",""8901""]],
                            UNIT[""degree"",0.01745329251994328,
                                AUTHORITY[""EPSG"",""9122""]],
                            AUTHORITY[""EPSG"",""4152""]],
                        PROJECTION[""Lambert_Conformal_Conic_2SP""],
                        PARAMETER[""standard_parallel_1"",48.73333333333333],
                        PARAMETER[""standard_parallel_2"",47.5],
                        PARAMETER[""latitude_of_origin"",47],
                        PARAMETER[""central_meridian"",-120.8333333333333],
                        PARAMETER[""false_easting"",500000],
                        PARAMETER[""false_northing"",0],
                        UNIT[""metre"",1,
                            AUTHORITY[""EPSG"",""9001""]],
                        AUTHORITY[""EPSG"",""2855""]]
                    "

                    // need other/more regions seach at https://epsg.io/ 
                    // the gibberish up there is the "Well Known Text (WKT)" look under "Export" or use short link e.g. https://epsg.io/4230.prettywkt
                });


        public static IPoint ProjectTo(this IPoint point, int fromSRID, int toSRID)
        {
            var transformation = _coordinateSystemServices.CreateTransformation(fromSRID, toSRID);
            var result = transformation.MathTransform.Transform(point.Coordinate);

            return new Point(result);
        }

        public static IGeometry ProjectTo(this IGeometry geometry, int fromSRID, int toSRID)
        {
            var transformation = _coordinateSystemServices.CreateTransformation(fromSRID, toSRID);
            var convertedCoords = new List<Coordinate>();

            foreach(var coord in  geometry.Coordinates)
            {
                var converted = transformation.MathTransform.Transform(coord);
                convertedCoords.Add(converted);
            }

            var result  = Geometry.DefaultFactory.CreatePolygon(convertedCoords.ToArray());
            return result;            
        }

    }
}
`
