### ISSUE TITLE
Missing dot separator between schema and table name for MsSql2008

### ISSUE THREAD

**Issue by mandersengeo** [nhibernate/NHibernate.Spatial#62]
Using NHibernate.Spatial.MsSql v4.0.4.4001 with MsSql2008GeographyDialect.

Schema export broke with:
NHibernate.HibernateException : Incorrect syntax near 'MyOtherwiseOkTable'
at NHibernate.Tool.hbm2ddl.SchemaExport.Execute

Examining the ddl output, I notice that directly after creating the view 
`[some_schema].[NHSP_GEOGRAPHY_COLUMNS]` 
\(with dot separator\), the script attempts to 
`ALTER [some_schema][MyOtherwiseOkTable] DROP COLUMN [Geometry] `
\(without dot separator\).

Adding a dot between schema and table name and re-running that db command, it runs fine.

It looks like in [MsSql2008FunctionRegistration.GetSpatialCreateString](https://github.com/nhibernate/NHibernate.Spatial/blob/master/NHibernate.Spatial.MsSql/Dialect/MsSql2008FunctionRegistration.cs#L548) the line
`			string quotedSchema = !string.IsNullOrEmpty(schema) ? adaptor.QuoteForSchemaName(schema) : string.Empty;
`
should instead be
`			string quotedSchema = adaptor.QuoteSchema(schema);
`
used elsewhere in that class, which does the null/empty check and otherwise appends StringHelper.Dot.

**Comment by andrerav** [comment]
Thanks @mandersengeo, this has been fixed and merged to master. I will publish a pre-release version of the NuGet packages ASAP.
