### ISSUE TITLE
Support NHibernate 4.1? 

### ISSUE THREAD

**Issue by EnemyArea** [nhibernate/NHibernate.Spatial#64]
Hi,
any chance to get an update for NHibernate 4.1 on nuget soon?
Thanks :D

**Comment by peetw** [comment]
Hi, have you tried NHibernate 4.1 with the current version(s) of NHibernate Spatial and the dialects? Were there any issues/bugs? I had a quick look at the release notes for 4.1 and it seems like it should be ok (the only changes that might affect NHibernate Spatial are the IndexOf indexing, although I didn't look too hard ;) )

**Comment by andrerav** [comment]
There are no immediate build errors or warnings, so I will go ahead and
submit a pull request for this and see how the build server responds.
Thanks for the heads up :)

**Comment by andrerav** [comment]
Here's the pull request: https://github.com/nhibernate/NHibernate.Spatial/pull/65

**Comment by andrerav** [comment]
Somewhat surprisingly, building for NH 4.1 seems to have fixed 3 failing tests in our test suite, and there are no new failing tests. Cool! I will merge the changes and publish new packages.

**Comment by peetw** [comment]
Oh nice! Out of interest, which ones were they?

**Comment by andrerav** [comment]
@EnemyArea Not sure yet, will dig into it. Meanwhile, some delicious prerelease packages are available for you on NuGet :)

**Comment by EnemyArea** [comment]
thank u :D

**Comment by peetw** [comment]
Were there any issues with the update in the end? Would it make sense to bump the pre-release to a full release?

**Comment by andrerav** [comment]
I haven't heard of any problems, so I'll publish new packages asap :)

**Comment by andrerav** [comment]
Packages for 4.1.0 are now online :)

**Comment by hazzik** [comment]
Hey, can you please update to 4.1.1? The 4.1.0 had some major problems.

**Comment by andrerav** [comment]
Hi @hazzik, thanks for the heads up! I will jump on that right away!

**Comment by andrerav** [comment]
Hi again @hazzik -- it seems that NHibernate 4.1.1 breaks 3 tests compared to NHibernate 4.1. Specifically, the following tests:

* ProjectionsFixture.OrderByDistanceLinq (MsSql2008)
* ProjectionsFixture.OrderByDistanceLinq (MySQL57)
* ProjectionsFixture.OrderByDistanceLinq (PostGis20)

It's easy to see that this relates to NH-3904 and NH-2401. IIt certinaly seems that I can change the tests to use the MappedAs() extension. And if that turns out to be correct, I believe there are a bunch of other failing tests I can fix in a similar manner.

**Comment by andrerav** [comment]
Alright, NH.Spatial 4.1.1 is available on NuGet, and I fixed the tests to accommodate NH-2401. Thanks @hazzik!

**Comment by peetw** [comment]
Shall we mark this issue as closed now, or is there more to do?

**Comment by andrerav** [comment]
Thanks @peetw, I think we should be all set, so I'm closing this issue now.
