### ISSUE TITLE
Cannot save 3D geometries to PostGIS

### ISSUE THREAD

**Issue by peetw** [nhibernate/NHibernate.Spatial#66]
Thanks to [IvoD for finding this bug](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/nhibernate-spatial/t8H8LyjbEg0/j4Kv0u48CgAJ).

I have replicated IvoD's issue using NHibernate.Spatial.PostGIS 4.0.4.4001. My entity class and FluentNHibernate mapping are as follows:

    public class Entity
    {
        public virtual int Id { get; set; }
        public virtual LineString Geom { get; set; }
    }

    public class EntityMap : ClassMap<Entity>
    {
        public EntityMap()
        {
            Id(x => x.Id);
            Map(x => x.Geom)
              .CustomType<PostGisGeometryType>()
              .CustomSqlType("geometry(LineStringZ)");
        }
    }

The test code to attempt to insert an entity with a 3D LineString:

    var line = new LineString(new[] { new Coordinate(0 1 2), new Coordinate(3 4 5), new Coordinate(6 7 8) });
    var entity = new Entity { Geom = line };
    using (var transaction = session.BeginTransaction())
    {
        session.Save(entity);
        transaction.Commit();
    }

The SQL emitted by NHibernate is as follows (tidied for clarity):

    UPDATE entity SET geom='0102000020346C0000030000000000000000000000000000000000F03F0000000000000840000000000000104000000000000018400000000000001C40';

which results in the following error:

    Npgsql.NpgsqlException: ERROR: 22023: Column has Z dimension but geometry does not

Indeed, if we run the following SQL query:

    SELECT ST_AsText('0102000020346C0000030000000000000000000000000000000000F03F0000000000000840000000000000104000000000000018400000000000001C40');

the result is:

    "LINESTRING(0 1,3 4,6 7)"

so we can clearly see that at some point along the way, the Z dimension has been stripped off.

The stripping of the Z values happens in the `PostGisGeometryType.FromGeometry()` method when using the `PostGisWriter` to [convert the geometry into WKB format](https://github.com/nhibernate/NHibernate.Spatial/blob/master/NHibernate.Spatial.PostGis/Type/PostGisGeometryType.cs#L65). This is because the [`HandleOrdinates`](https://github.com/NetTopologySuite/NetTopologySuite/blob/master/NetTopologySuite.IO/NetTopologySuite.IO.PostGis/PostGisWriter.cs#L21) property on the `PostGisWriter` defaults to `Ordinates.XY`.

The fix for this is to specify the `HandleOrdinates` property on the `PostGisWriter` prior to calling the `Write(geometry)` method based on the dimension (cardinality?) of the geometry being serialized. I'll submit a PR shortly.

I'll also have to investigate whether the `PostGisGeometryType.ToGeometry()` will need to be correspondingly updated...

**Comment by andrerav** [comment]
Excellent findings @peetw, as soon as the PR arrives I will run it through the test suite on the build server.
