### ISSUE TITLE
geometry is not loading after upgrade to 4.1.1 (previous 4.0.4) mssql

### ISSUE THREAD

**Issue by rjanetzek** [nhibernate/NHibernate.Spatial#69]
just updated nhibernate to 4.1.1 and noticed that our geometry is not loading. Saving the geometry is working.   After downgrading the lib, everything is working again. Anybody else having this issue?

**Comment by peetw** [comment]
There were a few breaking changes in the NHibernate update - see this issue for a summary: #64 

Can you copy and paste the exact error you are getting here?

**Comment by andrerav** [comment]
@rjanetzek I am going to venture a guess that your geometries are simply null and you are not getting any errors besides that. Is that correct?

**Comment by peetw** [comment]
Closing this due to lack of response from OP
