### ISSUE TITLE
HowTo: Pass IGeometry as parameter to query

### ISSUE THREAD

**Issue by FObermaier** [nhibernate/NHibernate.Spatial#7]
I implemented the ToGeometry static extension methods for Linq.
In the UnitTests where these functions play a role (the ones attributed Ignore("implement ToPolygon") I see that the IGeometry instance is being passed as parameter to the qurey and  not being converted to the db specific type. Therefor the tests fails.

Is there a way to instruct NHibernate to convert the parameter prior to passing it to the query?

**Comment by andrerav** [comment]
This should be possible to overcome now with NHibernate 4.1 and the new MappedAs() extension method. Here's an example on how to use it: https://github.com/nhibernate/NHibernate.Spatial/commit/0d74f8b4d0282d05faf5e9337e0f9abd5409cffe

@FObermaier I realize this is 2.5 years ago, but is there any chance you might give this a whirl? :)
