### ISSUE TITLE
MsSql2008 tests report false positives

### ISSUE THREAD

**Issue by peetw** [nhibernate/NHibernate.Spatial#72]
The connection string for the MsSql2008 test project specifies `Type System Version=SQL Server 2012`. When testing against a MS SQL Server 2008 instance (with 2012 also installed on the same system), this will result in many tests passing, when in fact they should fail due to non-support in 2008.

For example, the [spatial aggregate functions](https://docs.microsoft.com/en-us/sql/t-sql/spatial-geometry/static-aggregate-geometry-methods) were only added in 2012, so most of the `MsSql2008ProjectionsFixture.*` tests should fail when in fact they pass due to the use of the 2012 libs (see [the documentation](https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlconnection.connectionstring(v=vs.110).aspx) for the `Type System Version` connection string argument).

On my PC, changing the connection string to `Type System Version=SQL Server 2008` increases the number of failing tests from 8 to 51.

**Comment by peetw** [comment]
If someone can confirm this behaviour, I will create a PR fixing what tests I can and setting the rest to be ignored by the test runner.

**Comment by andrerav** [comment]
@peetw I'm pretty sure you are right about this. Please do submit a PR and I will verify the results on the build server.

**Comment by peetw** [comment]
Hmm, I think I messed up :see_no_evil: It turns out that `NHibernate.Spatial.MsSql` project references `Microsoft.SqlServer.Types, Version=11.0.0.0`, which corresponds to MsSql2012 and includes [breaking changes](https://msdn.microsoft.com/en-us/library/ms143179(v=sql.110).aspx) to the CLR geometry types compared to `Microsoft.SqlServer.Types, Version=10.0.0.0` used by MsSql2008. It was this incompatibility that was breaking the tests, not a lack of 2008 spatial features (on re-inspection, the aggregate function tests all fail correctly for the 2008 tests).

According to the previously linked article, there are two workarounds: 1) Create an assembly redirect in the app.config file, or 2) Specifying `Type System Version=SQL Server 2012` in the connection string to force SqlClient to load version 11.0 of the assembly.

There are a couple of tests that fail when they shouldn't so I'll fix those anyway and add a note to the app.config file for future contributors :stuck_out_tongue:
