### ISSUE TITLE
SchemaUpdate creates TINYINT column instead of GEOGRAPHY

### ISSUE THREAD

**Issue by darkengines** [nhibernate/NHibernate.Spatial#74]
Using MsSql2008GeographyDialect

```
//OK: Coordinates of type GEOGRAPHY
var exportScript = string.Empty;
new SchemaExport(configuration).Execute(s => exportScript = s, false, false);

//NOT OK: Coordinates of type TINYINT
var updateScript = string.Empty;
new SchemaUpdate(configuration).Execute(s => updateScript = s, false);
```

```
public class PolygonEntity
{
	public virtual Polygon Coordinates { get; set; }
	public virtual int Id { get; set; }
	public override string ToString()
	{
		return $"Polygon#{Id}";
	}
}
public class PolygonClassMap : ClassMap<PolygonEntity>
{
	public PolygonClassMap()
	{
		Id(polygon => polygon.Id);
		Map(polygon => polygon.Coordinates).CustomType<Wgs84GeographyType>();
	}
}
```

How can I generate an update script?
Do I miss something?

**Comment by peetw** [comment]
Hi @darkengines, it looks OK, but please could you post the definition for `Wgs84GeographyType` (I'm assuming you've defined that yourself?) and also the SQL generated by NHibernate in both cases (i.e. by `SchemaExport` and `SchemaUpdate`). Hopefully that should make it a bit easier to debug, thanks!

**Comment by darkengines** [comment]
@peetw, thanks for your reply.
Details bellow:

```
public class Wgs84GeographyType : MsSql2008GeographyType
{
	protected override void SetDefaultSRID(IGeometry geometry)
	{
		geometry.SRID = 4326;
	}
}
```

# exportScript =
```
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[NHSP_GEOGRAPHY_COLUMNS]'))
DROP VIEW [NHSP_GEOGRAPHY_COLUMNS];

EXECUTE('
CREATE VIEW [NHSP_GEOGRAPHY_COLUMNS] AS
SELECT
F_TABLE_CATALOG = cols.TABLE_CATALOG,
F_TABLE_SCHEMA = cols.TABLE_SCHEMA,
F_TABLE_NAME = cols.TABLE_NAME,
F_GEOMETRY_COLUMN = cols.COLUMN_NAME,
SRID = COALESCE(srid_checks.SRID, 0),
TYPE = COALESCE(type_checks.TYPE, ''GEOMETRY''),
COORD_DIMENSION = 2 -- TO-DO
FROM INFORMATION_SCHEMA.COLUMNS cols
LEFT JOIN (
	SELECT
	 TABLE_NAME = t.name
	,TABLE_SCHEMA = sc.name
	,COLUMN_NAME = c.name
	,SRID = CAST(
		SUBSTRING(
			ck.definition,
			CHARINDEX(''].[STSrid]=('', ck.definition) + 12,
			LEN(ck.definition) - CHARINDEX(''].[STSrid]=('', ck.definition) - 13
		)
		AS INTEGER
	)
	FROM sys.check_constraints ck, sys.schemas sc, sys.columns c, sys.tables t
	WHERE ck.schema_id = sc.schema_id
	AND ck.parent_column_id = c.column_id
	AND ck.parent_object_id = c.object_id
	AND CHARINDEX(''].[STSrid]=('', ck.definition) <> 0
	AND c.object_id = t.object_id
) as srid_checks
ON cols.TABLE_SCHEMA = srid_checks.TABLE_SCHEMA
AND cols.TABLE_NAME = srid_checks.TABLE_NAME
AND cols.COLUMN_NAME = srid_checks.COLUMN_NAME

LEFT JOIN (
	SELECT
	 TABLE_NAME = t.name
	,TABLE_SCHEMA = sc.name
	,COLUMN_NAME = c.name
	,TYPE = UPPER(
		SUBSTRING(
			ck.definition,
			CHARINDEX(''].[STGeometryType]()='''''', ck.definition) + 22,
			LEN(ck.definition) - CHARINDEX(''].[STGeometryType]()='''''', ck.definition) - 23
		)
	)
	FROM sys.check_constraints ck, sys.schemas sc, sys.columns c, sys.tables t
	WHERE ck.schema_id = sc.schema_id
	AND ck.parent_column_id = c.column_id
	AND ck.parent_object_id = c.object_id
	AND CHARINDEX(''].[STGeometryType]()='''''', ck.definition) <> 0
	AND c.object_id = t.object_id
) as type_checks
ON cols.TABLE_SCHEMA = type_checks.TABLE_SCHEMA
AND cols.TABLE_NAME = type_checks.TABLE_NAME
AND cols.COLUMN_NAME = type_checks.COLUMN_NAME

WHERE DATA_TYPE IN (''geography'')

')

;
ALTER TABLE [PolygonEntity] DROP COLUMN [Coordinates];ALTER TABLE [PolygonEntity] ADD [Coordinates] geography NULL;
```

# updateScript:
```
create table [PolygonEntity] (
	Id INT IDENTITY NOT NULL,
   Coordinates TINYINT null,
   primary key (Id)
)
```

The generated exportScript looks weird isn't it ? (The PolygonEntity table does not exist in the db yet).

**Comment by peetw** [comment]
Thanks for posting the output :) So, from the script generated by `SchemaExport`, I assume that you are adding a `SpatialAuxiliaryDatabaseObject` to your NHibernate configuration? During `SchemaExport`, NHibernate will apply the spatial ADO, which will convert the spatial database columns to the correct SQL type. However, NHibernate does not currently apply _any_ ADO's when running `SchemaUpdate`, so what you see in this case is the same SQL that would have been generated by `SchemaExport` as if you had not added the spatial ADO to the configuration.

To get the `SchemaUpdate` call to generate the correct SQL, you need to specify it as part of the mapping, i.e.:

    Map(polygon => polygon.Coordinates).CustomType<Wgs84GeographyType>().CustomSqlType("geography");

**Comment by darkengines** [comment]
Thank you for the explanation.
> I assume that you are adding a SpatialAuxiliaryDatabaseObject to your NHibernate configuration?
You are right:
`configuration.AddAuxiliaryDatabaseObject(new SpatialAuxiliaryDatabaseObject(configuration));`

**`.CustomSqlType("geography");` fixed the SQL column type.** 👍 

----------------------------------------

I still not understand where the ALTER comes from since there's no Polygon table at the export time. (Or maybe I missed somthing in the database):
`ALTER TABLE [PolygonEntity] DROP COLUMN [Coordinates];ALTER TABLE [PolygonEntity] ADD [Coordinates] geography NULL;`

**Comment by peetw** [comment]
If you change your `SchemaExport` call to:

    new SchemaExport(config).Execute(s => exportScript += s, false, false);

noting the `+=`, you'll see the full SQL generated, which does indeed include a `CREATE TABLE...` command.

**Comment by darkengines** [comment]
Oh OK. I haven't realized that the provided lambda may be called multiple times -_-.
Thanks for all.
