### ISSUE TITLE
Is the MsSqlLegacyDialect necessary?

### ISSUE THREAD

**Issue by peetw** [nhibernate/NHibernate.Spatial#76]
It appears as if it was originally created for use with the third-party [MsSqlSpatial](http://mssqlspatial.codeplex.com) extension for MS SQL 2005 databases. The first MS SQL server version to officially support spatial data was 2008.

I think it might be time to deprecate and remove it?

**Comment by andrerav** [comment]
There's no package for it on NuGet, and there never has been. My vote goes towards simply removing it altogether.

**Comment by peetw** [comment]
I would agree - I highly doubt anyone is actively using it, and if they are, we can make it clear in the release notes that it has been deprecated and removed. @suryapratap thoughts?

@andrerav  just to clarify, do you mean a NuGet package for the `MsSqlLegacyDialect` or the third-party MsSqlSpatial extension? Because isn't the `MsSqlLegacyDialect` included in the `NHibernate.Spatial.MsSql` NuGet package?

**Comment by andrerav** [comment]
@peetw Whoops, brainfart. Yes you are correct, the legacy dialect is included in the MsSql NuGet package :) I  would still prefer to have it removed though.

**Comment by suryapratap** [comment]
+1  The older Nuget packages will have the binaries, if anyone wants them at a later time they can put in a request.
