### ISSUE TITLE
Dialect database version requirements?

### ISSUE THREAD

**Issue by peetw** [nhibernate/NHibernate.Spatial#80]
I'm currently in the process of setting up my local PC (and also Appveyor CI) to run all of the test projects and it's not clear to me which versions of databases/extensions each dialect supports/is targeting?

I've put my best guesses in the table below and highlighted the ones I am unsure about. Does this look sensible?

| Test Project | Database | Extensions |
| --- | --- | --- |
| MsSql2008 | SQL Server 2008 Express R2 SP2 | N/a |
| MsSql2012 | SQL Server 2012 Express SP1 | N/a |
| MySQL | **MySQL 5.6** | N/a |
| MySQL57 | MySQL 5.7 | N/a |
| PostGis | **PostgreSQL 8.4** ~~or PostgreSQL 9.1?~~  | **PostGIS 1.5** |
| PostGis20 | PostgreSQL 9.6 | PostGIS 2.3 |

**Comment by andrerav** [comment]
The build server I am using is running SQL Server 2012, MySQL 5.7, and PostgreSQL 9.5. A more finely granulated set of database system versions would definitely be beneficial to keep track of backwards compatability. I think we should consider adding a dialect for MySQL 8 as well, lots of changes there compared to MySQL 5.7.

**Comment by peetw** [comment]
Good point re: MySQL 8 - will have to have a look to see what's changed!

As for testing, I've set up my fork to use AppVeyor CI (you can view the results [here](https://ci.appveyor.com/project/peetw/nhibernate-spatial/history)). I'll be submitting a PR once I've got all the tests passing :)

I ended up using the databases listed in the table above (using PostgreSQL 8.4 for the PostGis tests) - seems to be working OK!
