### ISSUE TITLE
Cant build from Master

### ISSUE THREAD

**Issue by jeffreyabecker** [nhibernate/NHibernate.Spatial#81]
NtsTestCasesFixture.cs has a reference to Open.Topology.TestRunner which I cant seem to find as a package.

**Comment by peetw** [comment]
If you open the `NHibernate.Spatial.sln` in VS 2015, it should include the `NetTopologySuite.TestRunner` project, which defines a bunch of `Xml*` classes in the `Open.Topology.TestRunner` namespace.

I _believe_ that these classes were taken from another project (most likely NTS), which would explain why the namespace doesn't match the standard naming convention... However, it shouldn't stop the solution from building?

**Comment by andrerav** [comment]
Master branch builds fine for me, and also on my rinky-dink build server.

**Comment by jeffreyabecker** [comment]
Ok, I'm seeing the problem now.  My machine doesn't have framework 3.5 installed and IT is blocking the installation.

**Comment by andrerav** [comment]
There are brand new packages on NuGet built from master yesterday, can you use those instead?

**Comment by jeffreyabecker** [comment]
I'll try. For some context, I:m trying to debug through and find the source of #82.

**Comment by peetw** [comment]
@jeffreyabecker Can't you just change the `NetTopologySuite.TestRunner` project to target .NET 4 Client Profile? I've not tested it, so I don't know if it would break anything (depends on what NuGet packages it requires I guess)

**Comment by jeffreyabecker** [comment]
There are some explicit references to net35 packages in there. I'll look at those when I get into the office

**Comment by jeffreyabecker** [comment]
Yes, fixing the explicit package references to 3.5 fixed it.
