### ISSUE TITLE
When using an Azure database, Geometry instances are always null

### ISSUE THREAD

**Issue by jeffreyabecker** [nhibernate/NHibernate.Spatial#82]
When running against an azure sql database, all the geometry instances are always null when they're read out of the database.

**Comment by peetw** [comment]
Hmm, I'm not too familiar with Azure - what version of MS SQL Server is your instance running?

**Comment by jeffreyabecker** [comment]
Azure Sql is a managed service that Microsoft provides in their cloud. It doesn't have a traditional version. Right now its roughly equivalent to 2016. However the app runs fine against my local machine's 2016 instance and the development server 2016 instance. We've also tested against everything from 2012 up. If you can provide some guidance on working around #81 I'll be able to get in and debug this.
