### ISSUE TITLE
Warn the custom type 'GeoAPI.Geometries.IGeometry' handled by ... is not Serializable

### ISSUE THREAD

**Issue by sh1ng** [nhibernate/NHibernate.Spatial#9]
But my custom type is Serializable

**Comment by EvK** [comment]
Hi, here is a link to stackoverflow discussion which maybe sheds some light on this issue: http://stackoverflow.com/q/35983333/5311735

**Comment by andrerav** [comment]
Thanks, will definitely take a new look at this!

**Comment by suryapratap** [comment]
This is a kind of knee jerk reaction.....

will this issue be resolved if we make the Parameter
```c#

public System.Type ReturnedType
{
    get { return typeof(IGeometry); }
}

```
into an abstract / virtual, this can be done in the  ```GeometryTypeBase<T>``` as it is an abstract class.

Then we can have the dialects each return the correct serializable type, it will also have an added benefit that the returned type will allow proper reflection.
 
The ```GeometryType``` class shows no references in the current code.

**Comment by suryapratap** [comment]
come to think of it an easier change would be 
```C#
public System.Type ReturnedType
        {
            get { return typeof(GeometryTypeBase<T>); }
        }
```

since ```GeometryTypeBase<T>``` is serializable

**Comment by EvK** [comment]
Don't think making ReturnedType virtual will help, because in several dialects there are several geometry types (line, polygon, etc) all implementing IGeometry - they won't be able to return concrete type.

Making it return GeometryTypeBase<T> _and_ making it virtual seems fine to me.

Though I proposed this solution for the problem day ago in parent repository: https://github.com/nhibernate/nhibernate-core/pull/469, to avoid such problems in future.

**Comment by suryapratap** [comment]
@EvK 
>Though I proposed this solution for the problem day ago in parent repository: nhibernate/nhibernate-core#469, to avoid such problems in future.

I am not a huge fan of if conditions. IMHO this change will cause similar issues in other custom types to be ignored. Returning an interface or abstract type causes loss of type information that could potentially be used by the consumer of the class I do not see any reason why the we should not return the proper type. 

```typeof(IGeometry)``` was a quick fix that worked well enough. Change with abstract class will Impact about 6 or 7 files, We will still need to see if that causes any tests to fail.

returning ```typeof(GeometryTypeBase<T>)``` will change only one file and still provide most of the benefits, making the parameter virtual will allow any dialect to override if necessary

**Comment by EvK** [comment]
Yes I agree your solution should be applied regardless of the state of my pull request, and it should fix this issue.

**Comment by andrerav** [comment]
Hi guys, the code you committed here had some nasty side effects. It broke schema export and SpatialRelationCriterion.GetColumnNames(). I think we should revert these changes (+ some of my changes made in error trying to fix some of the consequences).

**Comment by andrerav** [comment]
After further inspection I am fairly certain that these changes definitely need to be reverted. Warnings in the log are by far more tolerable than a broken library. I will submit a pull request ASAP.

**Comment by suryapratap** [comment]
My Bad, ```typeof( GeometryTypeBase<T>)``` was wrong type to be returned. 
Infact ```typeof(IGeometry)``` is the only option here since GeoAPI defines only the interface.

One thing to try would be to use the NTS classes instead of the GeoAPI interface
