### ISSUE TITLE
Nuget Release?

### ISSUE THREAD

**Issue by EnemyArea** [nhibernate/NHibernate.Spatial#91]
Hey ppl :D Can we get a stable release? It's still 5.0.0-pre1 on nuget.

**Comment by peetw** [comment]
I think this is only something that @andrerav or @suryapratap can deal with unfortunately.

**Comment by peetw** [comment]
Stable release packages for version 5.0.0 are now available on NuGet 🎉

**Comment by EnemyArea** [comment]
thank you very much :D
