### ISSUE TITLE
Add MySQL 8.0 spatial dialect

### ISSUE THREAD

**Issue by andrerav** [nhibernate/NHibernate.Spatial#93]
There are some [changes in the spatial functionality](https://mysqlserverteam.com/whats-new-in-mysql-8-0-generally-available/) in MySQL 8.0 compared to MySQL 5.7. We should add a separate dialect for MySQL 8.0 and implement any necessary changes. Spatial functionality has improved substantially in MySQL 8.0, so it should be worth the effort.

**Comment by peetw** [comment]
Sounds good! This [blog post](https://mysqlserverteam.com/upgrading-to-mysql-8-0-with-spatial-data/) on upgrading spatial data from MySQL 5.7 to 8.0 should be pretty useful guide.

Now, if only we could get Oracle to include my fix for the MySQL ADO.NET Connector...

**Comment by peetw** [comment]
@andrerav haha thanks for "encouraging" the MySQL team - I was beginning to think the fix might never make it in (especially based on the lifetime of some of the other bugs!!). Fingers crossed they release the new versions soon!

**Comment by andrerav** [comment]
I have been doing some testing with the new NH.Spatial 5.1 preview packages for MySQL, and things are looking very good. Stability and performance seems to be excellent so far. The data set I am using for testing currently consists of roughly 18 000 000 rows with geometries. Great job @peetw! This really paves the way for adding the new MySQL 8 geometric and geographical dialects.

**Comment by Amit-Joshi-Git** [comment]
Is there any update on this issue @andrerav ?
