### ISSUE TITLE
Support .NET Standard

### ISSUE THREAD

**Issue by peetw** [nhibernate/NHibernate.Spatial#96]
This will allow NHibernate.Spatial to be consumed from .NET Framework and .NET Core projects alike (and even Xamarin if you so desire!).

I will run the API analyzer tool to determine what is the lowest version of .NET Standard that we can target (and thus have the widest reach).

For reference: [.NET Standard version selector](http://immo.landwerth.net/netstandard-versions/)

**Comment by peetw** [comment]
So, just jotting down some tasks will need completing as part of this:

1. Update all NuGet packages to versions that support .NET Standard
2. Migrate solution from VS 2015 to VS 2017
3. Migrate each project from targeting .NET Framework to .NET Standard (might need to end up multi-targeting depending on the minimum version of .NET Framework / .NET Standard that we are required to support)

I'll be submitting a PR for item 1 shortly (once the latest version of [NetTopologySuite.IO.PostGis](https://www.nuget.org/packages/NetTopologySuite.IO.PostGis/) is pushed to NuGet). I'll then start working on items 2/3.

**Comment by peetw** [comment]
I've migrated all of the projects to .NET Standard 2.0 (see [this branch](/peetw/NHibernate.Spatial/tree/target-dotnet-standard)). The MySQL/PostGis projects seem to fine (they're passing the tests). However, MsSql is now failing since `Microsoft.SqlServer.Types` doesn't support .NET Standard (see #84). I tried using dotMorten's [.NET Standard re-implementation](https://github.com/dotMorten/Microsoft.SqlServer.Types), but there were a few compilation errors.

Essentially, I see two ways forward:
1. We revert back to .NET Framework for MsSql and use .NET Standard for MySQL/PostGis
2. We multi-target MsSql for both .NET Framework and .NET Standard (and try to fix dotMorten's implementation)

Option 1 is obviously much easier and something we could do straight away. Option 2 is messier and would involve us copying dotMorten's code into ours since there is no NuGet package (we could potentially do it via a git submodule). Anyway, what are your thoughts @andrerav ?

**Comment by dvdtth** [comment]
+1 for option 1. Is that the only thing stopping this from getting merged to master?

**Comment by andrerav** [comment]
Oh shoot, this has gone under my radar. I definitely support option 1 -- much less risk and we can always try migrating MSSQL again later.

**Comment by peetw** [comment]
Ok, I'll go with option 1 for now. The only thing left to do is to get the AppVeyor CI build working again. I should have some time next week to get it finished off and submit a PR.

**Comment by peetw** [comment]
Updated NuGet packages should now be available to download :tada:
